Farmazon/Controllers/FarmerProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Farmazon.Controllers
{
    [Authorize]
    public class FarmerProfileController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Farmazon/Controllers/ProductController.cs
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Farmazon.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();

            using (var context = new Farmazon_dbEntities())
            {
                var myItems = await context.Set<Inventory>().Where(x => x.SellerId.Equals(userId)).ToListAsync();

                if (myItems != null)
                {
                    return View();
                }
                return View(myItems);
            }
        }

        public async Task<ActionResult> GetInventory()
        {
            var userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();

            using (var context = new Farmazon_dbEntities())
            {
                var myItems = await context.Set<Inventory>().Where(x => x.SellerId.Equals(userId)).ToListAsync();

                if (myItems == null)
                {
                    return View();
                }

                return View(myItems);
            }
        }


        [HttpPost]
        public async Task<ActionResult> FillInventory(Inventory inventory)
        {
            using (var context = new Farmazon_dbEntities())
                {
                    var userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();

                    context.CreateInventoryItem(userId, inventory.Quantity, inventory.Price, inventory.ProductName, inventory.PhotoLocation, inventory.Description, inventory.ReviewCount, inventory.ReviewStars);
                    await context.SaveChangesAsync();

                    return new HttpStatusCodeResult((int)HttpStatusCode.OK);
                }
        }
    }
}

Farmazon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Farmazon - Connect to Local Farmers!</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="logo"><i class="fas fa-tractor"></i></div>
                @Html.ActionLink("Farmazon", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Market", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("My Products", "Index", "Product", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Farmer Profile", "Index", "FarmerProfile", new { area = "" }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Farmazon</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>